cityfood/cityfood/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps import FlatPageSitemap


sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = patterns(
    '',
    url(r'^$', 'cityfood.views.home', name='home'),
    url(r'^order/', include('order.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^robots\.txt$', include('robots.urls')),
    url(
        r'^sitemap\.xml$',
        'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

if getattr(settings, 'DEBUG', False):
    urlpatterns += patterns(
        'django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': getattr(settings, 'MEDIA_ROOT', ''),
            'show_indexes': True,
            }),
    )

cityfood/order/urls.py
# coding: utf-8
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'order.views',
    url(r'success/$', 'order_success', name='order_success'),
    url(r'$', 'order', name='order'),
)

cityfood/order/models.py
# coding: utf-8
from django.db import models


class OrderStatus(models.Model):
    name = models.CharField(u'Название', max_length=100)
    position = models.IntegerField(u'Позиция', default=1)
    default = models.BooleanField(u'По умолчанию', default=False)

    class Meta:
        ordering = ['position']
        verbose_name = u'Статус заказа'
        verbose_name_plural = u'Статусы заказов'

    def __unicode__(self):
        return self.name


class Order(models.Model):
    name = models.CharField(u'Имя', max_length=200)
    phone = models.CharField(u'Телефон', max_length=50)
    address = models.TextField(u'Адрес доставки')
    comment = models.TextField(u'Комментарий', blank=True)

    purchase_price = models.DecimalField(
        u'Цена в закупке', max_digits=5, decimal_places=2)
    price = models.DecimalField(u'Цена', max_digits=5, decimal_places=2)
    status = models.ForeignKey(OrderStatus, verbose_name=u'Статус')

    added = models.DateTimeField(u'Добавлен', auto_now_add=True)
    modified = models.DateTimeField(u'Изменен', auto_now=True)

    class Meta:
        ordering = ['-added']
        verbose_name = u'Заказ'
        verbose_name_plural = u'Заказы'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name=u'Заказ')
    product = models.ForeignKey('catalog.Product', verbose_name=u'Товар')
    amount = models.IntegerField(u'Количество')

    purchase_price_for_one = models.DecimalField(
        u'Цена за единицу в закупке',
        max_digits=5, decimal_places=2)
    purchase_price = models.DecimalField(
        u'Цена за позицию в закупке',
        max_digits=5, decimal_places=2)

    price_for_one = models.DecimalField(
        u'Цена за единицу',
        max_digits=5, decimal_places=2)
    price = models.DecimalField(
        u'Цена за позицию',
        max_digits=5, decimal_places=2)

    class Meta:
        verbose_name = u'Элемент заказа'
        verbose_name_plural = u'Элементы заказа'

    def __unicode__(self):
        return unicode(self.product)

cityfood/order/forms.py
# coding: utf-8
from django import forms


class OrderForm(forms.Form):
    name = forms.CharField(label=u'Имя')
    phone = forms.CharField(label=u'Телефон')
    address = forms.CharField(label=u'Адрес доставки')
    comment = forms.CharField(
        label=u'Комментарий',
        required=False, widget=forms.Textarea)

cityfood/order/views.py
# coding: utf-8
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response, redirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from .forms import OrderForm
from .models import Order, OrderItem, OrderStatus
from django.core.mail import send_mail
from django.conf import settings


def order(request):
    from catalog.models import Product
    products = Product.objects.filter(active=True)

    non_active = Product.objects.filter(active=False)
    products = products.exclude(linked_products__in=non_active)
    products = products.order_by('category__position', 'position')

    selected_product = request.GET.get('product')
    if selected_product:
        try:
            selected_product = int(selected_product)
        except:
            selected_product = None

    _c = None
    for p in products:
        if p.category.name != _c:
            p.printed_category = p.category.name
            _c = p.category.name

    form = OrderForm()
    if request.method == 'POST':
        data = request.POST
        form = OrderForm(data)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            phone = form.cleaned_data.get('phone')
            address = form.cleaned_data.get('address')
            comment = form.cleaned_data.get('comment')

            email_body = u'''
Данные пользователя
-------------------------------
Имя: {name}
Телефон: {phone}
Адрес: {address}
Комментарий: {comment}
-------------------------------
            '''.format(
                name=name,
                phone=phone,
                address=address,
                comment=comment,
            )

            status = OrderStatus.objects.get(default=True)
            order = Order(
                name=name,
                phone=phone,
                address=address,
                comment=comment,
                price=0,
                purchase_price=0,
                status=status,
            )
            order.save()

            order_price = 0
            order_purchase_price = 0
            for product in products:
                _amount = request.POST.get('product-amount-%d' % product.id)
                if _amount:
                    try:
                        amount = int(_amount)
                        if amount > 0:
                            orderitem = OrderItem(
                                order=order,
                                product=product,
                                amount=amount,
                                purchase_price_for_one=product.purchase_price,
                                purchase_price=product.purchase_price*amount,
                                price_for_one=product.price,
                                price=product.price*amount,
                            )
                            orderitem.save()
                            order_price += product.price * amount
                            order_purchase_price += product.purchase_price * amount
                            email_body += u'''
{product:<30}  |  {price_for_one} грн.  |  {amount}  |  {price} грн.
                            '''.format(
                                product=product.name,
                                amount=amount,
                                price_for_one=product.price,
                                price=product.price*amount,
                            )
                    except:
                        pass
            order.price = order_price
            order.purchase_price = order_purchase_price
            order.save()
            email_body += u'''
-------------------------------
Всего: {price} грн.
В закупке: {purchase_price} грн.
            '''.format(
                price=order_price,
                purchase_price=order_purchase_price,
            )

            # Send email to managers here
            send_mail(
                u'Новый заказ на Cityfood',
                email_body,
                settings.DEFAULT_FROM_EMAIL,
                settings.MANAGER_EMAILS,
                fail_silently=False,
            )

            return redirect(reverse('order_success')+'?order=%d' % order.id)

    return render_to_response(
        'order/order.html', RequestContext(request, {
            'products': products,
            'form': form,
            'selected_product': selected_product,
        }))


def order_success(request):
    order_id = request.GET.get('order')

    if order_id:
        try:
            order = Order.objects.get(id=order_id)
        except Order.DoesNotExist:
            raise Http404
    else:
        raise Http404

    return render_to_response(
        'order/order_success.html', RequestContext(request, {
            'order': order,
        }))

cityfood/order/templates/order/order.html
{% extends "base.html" %}
{% load i18n l10n %}
{% load crispy_forms_tags %}

{% block title %}CityFood - Заказ блюд для доставки комплексных обедов в офисы Полтавы{% endblock %}
{% block meta_keywords %}cityfood, ситифуд, меню, список, обеды, комплексные, офис, блюдо, полтава{% endblock %}

{% block content %}
<h1>Сегодняшнее меню:</h1>
<form method="post">
{% csrf_token %}
<div class="panel-group" id="accordion">


{% for product in products %}
{% if product.printed_category %}
{% if not forloop.first %}
</table>
</div></div></div>
{% endif %}
<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-{{ product.category.pk }}">
          {{ product.printed_category }}
        </a>
      </h4>
    </div>
    <div id="collapse-{{ product.category.pk }}" class="panel-collapse collapse {% if forloop.first %}in{% endif %}">
      <div class="panel-body">
<table class="table order-table table-striped table-bordered product-list">
{% endif %}
<tr>
<td>
<a class="image-popup" href="/media/{{ product.image }}"
title="{{ product.name }}">
<img src="/media/{{ product.image }}" style="width:100px;">
</a>
</td>
<td>
<h4 class="product-name">{{ product.name }}</h4>
<p>{{ product.description }}</p>
</td>
<td>
<div class="product-price" id="product-price-{{ product.id }}" data-price="{{ product.price|unlocalize }}">{{ product.price|floatformat:2 }} грн.</div>
<input class="order--product-amount" name="product-amount-{{ product.id }}" id="product-amount-{{ product.id }}" type="number"
value="{% if selected_product == product.id %}1{% else %}0{% endif %}">
</td></tr>
{% if forloop.last %}
</table>
</div></div></div>
{% endif %}
{% endfor %}
<table class="table">
<tr>
<td colspan="3" style="text-align:right;">
<h4 class="text-info">Всего: <span id="order-price-total">0</span> грн.</h4>
</td>
</tr>
</table>

</div>
{{ form|crispy }}

<input class="btn btn-primary" type="submit" value="Оформить заказ">
</form>

<script type="text/javascript">
function refresh_total_price() {
    var total_price = 0;
    var p, a;

    {% for product in products %}
    p = parseFloat($("#product-price-{{ product.id }}").data("price"));
    a = parseInt($("#product-amount-{{ product.id }}").val());
    total_price = total_price + p * a;
    {% endfor %}
    $('#order-price-total').html(total_price);
}

refresh_total_price();
$(".order--product-amount").change(refresh_total_price);

$(document).ready(function() {
    $('.product-list').magnificPopup({
        delegate:'a.image-popup',
        type:'image',
        gallery: { enabled:true },
        image: { titleSrc: 'title' }
    });
});
</script>
{% endblock %}

cityfood/order/templates/order/order_success.html
{% extends "base.html" %}

{% block content %}
<h2>Спасибо за заказ</h2>

<p>Ваш запрос успешно принят в обработку. Скоро мы вам перезвоним.</p>

<table class="table table-bordered">
<tr>
    <th>Изображение</th>
    <th>Название</th>
    <th>Количество</th>
    <th>Цена</th>
</tr>
{% for item in order.orderitem_set.all %}
<tr>
    <td><img src="/media/{{ item.product.image }}" style="width:100px;"></td>
    <td>{{ item.product.name }}</td>
    <td>{{ item.amount }}</td>
    <td>{{ item.price }} грн.</td>
</tr>
{% endfor %}
<tr>
    <td colspan="3"><strong class="pull-right">Всего:</strong></td>
    <td><strong>{{ order.price }} грн.</strong></td>
</tr>
</table>
{% endblock %}

cityfood/order/templates/order/print_order.html
{% extends "clear.html" %}

{% block title %}Заказы{% endblock %}

{% block content %}
<h1>Список заказов</h1><hr/>
{% for order in orders %}
<h2>Заказ № {{ order.id }}</h2>
<p>Добавлен: {{ order.added }}</p>
<table class="table table-bordered table-striped">
<tr>
    <th>Имя</th>
    <th>Телефон</th>
    <th>Адрес доставки</th>
    <th>Комментарий</th>
</tr>
<tr>
    <td>{{ order.name }}</td>
    <td>{{ order.phone }}</td>
    <td>{{ order.address }}</td>
    <td>{{ order.comment }}</td>
</tr>
</table>
<table class="table table-bordered table-striped">
<tr>
    <th>№</th>
    <th>Название</th>
    <th>Цена за шт (грн.)</th>
    <th>Количество</th>
    <th>Цена (грн.)</th>
    <th>Заметки</th>
</tr>
{% for item in order.orderitem_set.all %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ item.product.name }}
    {% if item.product.linked_products.count > 0 %}
        <br/><ul>
        {% for i in item.product.linked_products.all %}
        <li>{{ i.name }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    </td>
    <td>{{ item.price_for_one }}</td>
    <td>{{ item.amount }}</td>
    <td>{{ item.price }}</td>
    <td></td>
</tr>
{% endfor %}
<tr>
    <td colspan="4"><strong class="pull-right">Всего:</strong></td>
    <td colspan="2"><strong>{{ order.price }} грн.</strong></td>
</tr>    
</table>
<p>Статус заказа</p>
<table class="table table-bordered table-striped">
<tr>
{% for status in order_statuses %}<th>{{ status.name }}</th>{% endfor %}
</tr>
<tr>
{% for status in order_statuses %}<td>&nbsp;</td>{% endfor %}
</tr>
</table>
{% endfor %}
<h1>Список для закупки</h1><hr/>
<h2>Блюда</h2>
<table class="table table-bordered table-striped">
<tr>
    <th>№</th>
    <th>Название</th>
    <th>Цена в закупке за шт. (грн.)</th>
    <th>Цена за шт. (грн.)</th>
    <th>Количество</th>
    <th>Цена в закупке (грн.)</th>
    <th>Цена (грн.)</th>
</tr>
{% for p in products_for_purchase %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ p.product.name }}</td>
    <td>{{ p.purchase_price_for_one }}</td>
    <td>{{ p.price_for_one }}</td>
    <td>{{ p.amount }}</td>
    <td>{{ p.purchase_price }}</td>
    <td>{{ p.price }}</td>
</tr>
{% endfor %}
<tr>
    <td colspan="5" style="text-align:right;"><strong>Всего:</strong></td>
    <td><strong>{{ purchase_price }} грн.</strong></td>
    <td><strong>{{ total_price }} грн.</strong></td>
</tr>
</table>

<h2>Упаковка</h2>
<table class="table table-bordered table-striped">
<tr>
    <th>№</th>
    <th>Название</th>
    <th>Количество</th>
</tr>
{% for b in boxing %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ b.0}}</td>
    <td>{{ b.1 }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}